python:
#  - 2.7.*
  #- 3.6.*
  - 3.7.* # [not arm64]
  - 3.8.* 
  - 3.9.*
  - 3.10.*
  - 3.11.*
  #- 3.12.*   # not compatible with setuptools <60.0
  #- 3.13.*   # not compatible with setuptools <60.0
numpy:
  - 1.22.*  #build against an old numpy to ensure backwards compatibiloity
  - 1.22.*
  - 1.22.*
  - 1.22.*
  - 1.23.*
   

zip_keys:
  - python
  - numpy
#  - 1.11.* # [py2k]

#- 1.13
