# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

#just build a single, lightweight, dependency to troubleshoot

name: Build PYMECompress

on:
  workflow_dispatch:

jobs:

  nix:
    strategy:
      matrix:
        os: [ubuntu-latest] #windows-latest, macos-latest]
        python: ['3.7'] #,2.7] - # 2.7 disabled for now due to missing VC9

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python }}
    - name: Conda info
      run: |
        conda info
        conda list
    - name: Install dependencies
      run: |
        conda install conda-build anaconda-client
        mkdir ~/pkg_build
    - name: Build and publish
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        export ANACONDA_API_TOKEN=$ANACONDA_TOKEN
        conda build --output-folder ~/pkg_build --skip-existing -c david_baddeley pymecompress 
        #ls -al ~/pkg_build/linux-64
        if compgen -G "~/pkg_build/linux-64/*.conda" > /dev/null; then
          /usr/share/miniconda/bin/anaconda -v --show-traceback upload -u david_baddeley --force ~/pkg_build/linux-64/*.conda
        fi
        #/usr/share/miniconda/bin/anaconda -v --show-traceback upload -u david_baddeley --force ~/pkg_build/linux-64/*.conda


  osx:
    strategy:
      matrix:
        os: [macos-latest] #windows-latest, macos-latest]
        architecture: ['x86_64', 'arm64']
        python: ['3.8'] #,2.7] - # 2.7 disabled for now due to missing VC9

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python }}
        #mamba-version: "*"
        architecture: ${{ matrix.architecture }}
        miniforge-version: "latest"
    - name: Conda info
      run: |
        conda info
        conda list
    - name: Install dependencies
      run: |
        conda install conda-build anaconda-client
        mkdir ~/pkg_build
    - name: Build and publish
      shell: bash #force bash shell to avoid issues with conditonals
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        export ANACONDA_API_TOKEN=$ANACONDA_TOKEN
        conda build --output-folder ~/pkg_build --skip-existing -c david_baddeley pymecompress 
        ls -al ~/pkg_build/
        if compgen -G "~/pkg_build/osx-64/*.conda" > /dev/null; then
          /Users/runner/miniconda3/bin/anaconda -v --show-traceback upload -u david_baddeley --force ~/pkg_build/osx-64/*.conda
        fi
        if compgen -G "~/pkg_build/osx-arm64/*.conda" > /dev/null; then
          /Users/runner/miniconda3/bin/anaconda -v --show-traceback upload -u david_baddeley --force ~/pkg_build/osx-arm64/*.conda
        fi
       


  win:
    strategy:
      matrix:
        os: [windows-latest] #windows-latest, macos-latest]
        python: ['3.7',] #,2.7] - # 2.7 disabled for now due to missing VC9

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python }}
    - name: Conda info
      run: |
        conda info
        conda list
    - name: Install dependencies
      shell: pwsh
      run: |
        conda install conda-build anaconda-client
        mkdir ~/pkg_build
    - name: Build and publish
      shell: pwsh
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        #mv setup.cfg.win setup.cfg
        conda build --skip-existing -c david_baddeley pymecompress
        #ls -al ~/pkg_build/linux-64
        #ls C:\Miniconda\Scripts\
        #ls C:\Miniconda\bin\
        #ls C:\Miniconda\envs\test\Scripts
        C:\Miniconda\envs\test\Scripts\anaconda.exe -v --show-traceback upload -u david_baddeley --force C:\Miniconda\envs\test\conda-bld\win-64\*.tar.bz2
